# Generated by Django 3.2.5 on 2021-11-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HypervisorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esxi_hostname', models.CharField(max_length=100)),
                ('esxi_username', models.CharField(max_length=100)),
                ('esxi_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Selected_vms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_guestHostname', models.CharField(max_length=100)),
            ],
        ),
    ]
