# Generated by Django 2.1.15 on 2021-11-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patching', '0002_delete_selected_vms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervisorinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
